[package]
name = "cellular"
version = "0.1.0"
authors = ["David Maynard <davidsmaynard@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
